services:
  category-service:
    build:
      context: .
      dockerfile: Dockerfile.category
    container_name: expense-tracker-category-service
    env_file:
      - .env
    ports:
      - "5001:5001"
    volumes:
      - ./backend/category-service:/app
    depends_on:
      - mongo

  expense-service:
    build:
      context: .
      dockerfile: Dockerfile.expense
    container_name: expense-tracker-expense-service
    env_file:
      - .env
    ports:
      - "5002:5002"
    volumes:
      - ./backend/expense-service:/app
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: expense-tracker-frontend
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo
    container_name: expense-tracker-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
